import React from "react";
import { motion, AnimatePresence } from "framer-motion";
import { PlayCircle, ArrowRight } from "lucide-react";

const SummaryCard = ({ summary }) => {
  return (
    <AnimatePresence>
      {summary && (
        <motion.div
          initial={{ y: 50, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          exit={{ y: 50, opacity: 0 }}
          className="mt-4 sm:mt-1 max-w-4xl mx-auto"
        >
          <div className="bg-white/10 backdrop-blur-2xl border border-white/20 rounded-3xl p-6 sm:p-8 shadow-2xl">
            
            <div className="flex items-center gap-3 mb-4 sm:mb-6">
              <PlayCircle className="w-8 h-8 sm:w-10 sm:h-10 text-cyan-400" />
              <h3 className="text-xl sm:text-2xl font-bold">Video Summary</h3>
            </div>

            {/* SUMMARY ARTIK HTML / RICH TEXT OLARAK GELİR */}
            <div
              className="text-base sm:text-lg leading-relaxed text-gray-200 prose prose-invert"
              dangerouslySetInnerHTML={{ __html: summary }}
            />

            <div className="mt-6 sm:mt-8 pt-4 sm:pt-6 border-t border-white/10 flex justify-between items-center">
              <span className="text-xs sm:text-sm text-gray-400">
                Generated by AI • Saved time
              </span>
             
            </div>
          </div>
        </motion.div>
      )}
    </AnimatePresence>
  );
};

export default SummaryCard;
